// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxGfnYFHvQXuFjsSIv4l2aX8HoD2Damx4',
    appId: '1:781840244242:android:33abe7c3a90bfd4cd802cb',
    messagingSenderId: '781840244242',
    projectId: 'cryptowallet-decimo',
    storageBucket: 'cryptowallet-decimo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkCi3qshDgJ75vLPpB0XdB2Z1YHrwHb6w',
    appId: '1:781840244242:ios:22dd4c40808fb644d802cb',
    messagingSenderId: '781840244242',
    projectId: 'cryptowallet-decimo',
    storageBucket: 'cryptowallet-decimo.appspot.com',
    androidClientId: '781840244242-4536bphnsq6f7aoj5udjgn9i1e4681q3.apps.googleusercontent.com',
    iosClientId: '781840244242-ob5ejbuvb7eenr6tkuj1ole5nnrk8ss9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkCi3qshDgJ75vLPpB0XdB2Z1YHrwHb6w',
    appId: '1:781840244242:ios:22dd4c40808fb644d802cb',
    messagingSenderId: '781840244242',
    projectId: 'cryptowallet-decimo',
    storageBucket: 'cryptowallet-decimo.appspot.com',
    androidClientId: '781840244242-4536bphnsq6f7aoj5udjgn9i1e4681q3.apps.googleusercontent.com',
    iosClientId: '781840244242-ob5ejbuvb7eenr6tkuj1ole5nnrk8ss9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoWallet',
  );
}
